services:
  configserver:
    image: ritzzikukg/configserver:2.0.0
    container_name: configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ijp
  eurekaserver:
    image: ritzzikukg/eurekaserver:2.0.0
    container_name: eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - ijp
  ijp:
    image: ritzzikukg/ijp:1.0.0
    container_name: "application"
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent localhost:8020/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "IJP"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"

    depends_on:
      eurekaserver:
        condition: service_healthy
    networks:
      - ijp
  jobpostijp:
    image: ritzzikukg/jobpostijp:1.0.0
    container_name: "jobPost"
    ports:
      - "8082:8082"
    healthcheck:
      test: "curl --fail --silent localhost:8040/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "JobPostIJP"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"

    depends_on:
      eurekaserver:
        condition: service_healthy
    networks:
      - ijp

  gatewayserver:
    image: ritzzikukg/gatewayserver:2.0.0
    container_name: "gatewayserver"
    ports:
      - "8072:8072"
    healthcheck:
      test: "curl --fail --silent localhost:8072/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
    depends_on:
      ijp:
        condition: service_healthy
      jobpostijp:
        condition: service_healthy

    networks:
      - ijp

networks:
  ijp:
    driver: "bridge"